import assert from 'node:assert/strict'
import test from 'node:test'

import {
  commitMessageViolations,
  listOutgoingCommits,
  parseGitIdent,
  parsePushUpdates,
  runPrePush,
  validateCommitMessage,
  validateEffectiveIdentities,
  validateOutgoingCommit,
} from '../identity-guard.mjs'

const lock = {
  account: 'alice',
  authorName: 'Alice Example',
  authorEmail: 'alice@example.test',
}

test('commit-message policy blocks AI attribution trailers and generation disclosures', () => {
  const blocked = [
    'Ship feature\n\nCo-authored-by: Claude <noreply@anthropic.com>',
    'Ship feature\n\nGenerated-by: ChatGPT',
    'Ship feature\n\nAssisted-by: GitHub Copilot',
    'Ship feature\n\nThis commit was generated by AI.',
    'Ship feature\n\nGenerated with GitHub Copilot.',
    'Ship feature\n\nThis patch was written using Claude Code.',
    'Ship feature\n\nThis commit was generated\nby ChatGPT.',
    'Ship feature\n\nI used Codex to write this change.',
    'Claude-assisted commit',
  ]
  for (const message of blocked) {
    assert.throws(() => validateCommitMessage(message), /Commit message rejected/)
    assert.ok(commitMessageViolations(message).length > 0)
  }
})

test('commit-message policy permits product features that genuinely discuss AI', () => {
  const allowed = [
    'Add AI-generated commit message previews',
    'Fix Copilot terminal integration',
    'Document how the AI assistant creates a session',
    'Add Generated-by field parsing for imported data',
    'Pair on identity guard\n\nCo-authored-by: Bob Human <bob@example.test>',
  ]
  for (const message of allowed) assert.doesNotThrow(() => validateCommitMessage(message))
})

test('pre-commit identity validation requires both effective identities to match exactly', () => {
  const matching = { name: lock.authorName, email: lock.authorEmail }
  assert.doesNotThrow(() => validateEffectiveIdentities({ author: matching, committer: matching }, lock))
  assert.throws(
    () => validateEffectiveIdentities({ author: { name: 'Other', email: 'other@example.test' }, committer: matching }, lock),
    /author is Other/,
  )
  assert.deepEqual(parseGitIdent('Alice Example <alice@example.test> 1786250000 +0700'), matching)
  assert.throws(() => parseGitIdent('not an ident'), /invalid effective identity/)
})

test('outgoing commits require the locked committer but preserve a cherry-picked author', () => {
  const ownCommit = {
    sha: 'a'.repeat(40),
    authorName: lock.authorName,
    authorEmail: lock.authorEmail,
    committerName: lock.authorName,
    committerEmail: lock.authorEmail,
  }
  assert.deepEqual(validateOutgoingCommit(ownCommit, lock), { preservedAuthor: false })
  assert.deepEqual(validateOutgoingCommit({
    ...ownCommit,
    authorName: 'Original Author',
    authorEmail: 'original@example.test',
  }, lock), { preservedAuthor: true })
  assert.throws(() => validateOutgoingCommit({
    ...ownCommit,
    committerName: 'Wrong Committer',
  }, lock), /has committer Wrong Committer/)
})

test('pre-push input parsing and local-only revision selection handle updates and deletions', () => {
  const local = 'a'.repeat(40)
  const remote = 'b'.repeat(40)
  const zero = '0'.repeat(40)
  const updates = parsePushUpdates([
    `refs/heads/feature ${local} refs/heads/feature ${remote}`,
    `refs/heads/delete ${zero} refs/heads/delete ${remote}`,
  ].join('\n'))
  const calls = []
  const runner = (command, args) => {
    calls.push([command, ...args])
    if (args[0] === 'cat-file') return { status: 0, stdout: '', stderr: '' }
    if (args[0] === 'rev-list') return { status: 0, stdout: `${'c'.repeat(40)}\n${'d'.repeat(40)}\n`, stderr: '' }
    throw new Error(`Unexpected command: ${command} ${args.join(' ')}`)
  }
  assert.deepEqual(listOutgoingCommits(updates, 'origin', { runner }), ['c'.repeat(40), 'd'.repeat(40)])
  assert.equal(calls.filter((call) => call[1] === 'rev-list').length, 1)
  assert.deepEqual(calls.find((call) => call[1] === 'rev-list'), [
    'git', 'rev-list', local, '--not', remote, '--remotes=origin',
  ])
  assert.throws(() => parsePushUpdates('invalid input'), /invalid pre-push ref update/)
})

test('pre-push verifies the locked HTTPS credential before accepting local-only commits', () => {
  const local = 'a'.repeat(40)
  const outgoing = 'c'.repeat(40)
  const zero = '0'.repeat(40)
  const config = new Map([
    ['omniterm.identity.account', lock.account],
    ['omniterm.identity.authorName', lock.authorName],
    ['omniterm.identity.authorEmail', lock.authorEmail],
    ['user.name', lock.authorName],
    ['user.email', lock.authorEmail],
    ['credential.username', lock.account],
    ['credential.https://github.com.useHttpPath', 'true'],
  ])
  const calls = []
  const runner = (command, args, options = {}) => {
    calls.push({ command, args, options })
    if (command === 'git' && args[0] === 'config') {
      const value = config.get(args.at(-1))
      return value === undefined ? { status: 1, stdout: '', stderr: '' } : { status: 0, stdout: `${value}\n`, stderr: '' }
    }
    if (command === 'git' && args[0] === 'remote') {
      return { status: 0, stdout: 'https://alice@github.com/owner/repo\n', stderr: '' }
    }
    if (command === 'git' && args.includes('fill')) {
      assert.match(options.input, /username=alice/)
      return { status: 0, stdout: 'username=alice\npassword=https-token\n', stderr: '' }
    }
    if (command === 'gh' && args[0] === 'api') {
      assert.equal(options.env.GH_TOKEN, 'https-token')
      return { status: 0, stdout: 'alice\n', stderr: '' }
    }
    if (command === 'git' && args[0] === 'rev-list') return { status: 0, stdout: `${outgoing}\n`, stderr: '' }
    if (command === 'git' && args[0] === 'show' && args[2].includes('%an')) {
      return { status: 0, stdout: `${lock.authorName}\0${lock.authorEmail}\0${lock.authorName}\0${lock.authorEmail}\n`, stderr: '' }
    }
    if (command === 'git' && args[0] === 'show') return { status: 0, stdout: 'Add guarded push\n', stderr: '' }
    throw new Error(`Unexpected command: ${command} ${args.join(' ')}`)
  }

  const result = runPrePush(
    'origin',
    'https://alice@github.com/owner/repo',
    `refs/heads/feature ${local} refs/heads/feature ${zero}\n`,
    { runner },
  )
  assert.deepEqual(result, { account: 'alice', commitsChecked: 1 })
  assert.ok(calls.findIndex((call) => call.command === 'gh') < calls.findIndex((call) => call.args[0] === 'rev-list'))
})
